#service loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: default
spec:
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
