#service loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: default
spec:
  selector:
    app: shop-app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
